apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mssql-depl-prod
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: mssql-prod
    template: 
        metadata: 
            labels:
                app: mssql-prod
        spec: 
            containers: 
                - name: mssql-prod
                  image: mcr.microsoft.com/azure-sql-edge:latest
                  ports:
                    - containerPort: 1433
                  env: 
                    - name: MSSQL_PID
                      value: "Developer"
                    - name: ACCEPT_EULA
                      value: "Y"
                    - name: SA_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mssql
                          key: SA_PASSWORD
                    - name: MSSQL_AGENT_ENABLED
                      value: "TRUE"
                    - name: MSSQL_COLLATION
                      value: "SQL_Latin1_General_CP1_CI_AS"
                    - name: MSSQL_LCID
                      value: "1033"
                  volumeMounts: 
                    - mountPath: /var/opt/mssql/data
                      name: mssqldb-prod
            volumes: 
                - name: mssqldb-prod
                  persistentVolumeClaim: 
                    claimName: mssql-claim-prod
---
apiVersion: v1
kind: Service
metadata:
    name: mssql-clusterip-prod
spec:
    type: ClusterIP
    selector:
        app: mssql-prod
    ports:
        - name: mssql-prod
          protocol: TCP
          port: 1434
          targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
    name: mssql-loadbalancer-prod
spec:
    type: LoadBalancer
    selector:
        app: mssql-prod
    ports:
         - protocol: TCP
           port: 1434
           targetPort: 1433
