apiVersion: apps/v1
kind: Deployment
metadata:
    name: lepicka-products-depl
spec:
    replicas: 1
    selector: 
        matchLabels: 
            app: lepicka-products
    template:
        metadata:
            labels:
                app: lepicka-products
        spec:
            containers:
                - name: lepicka-products
                  image: saeqis/lepicka:products-pi
                  env: 
                    - name: CONNECTION_STRING_CREDS
                      valueFrom: 
                        secretKeyRef:
                            name: db-creds
                            key: products-db
---
apiVersion: v1
kind: Service
metadata:
    name: lepicka-products-clusterip-srv
spec:
    type: ClusterIP
    selector:
        app: lepicka-products
    ports:
        - name: lepicka-products
          protocol: TCP
          port: 8080
          targetPort: 8080